using System.Text;
using PwaDrop.App.Interop;

namespace PwaDrop.DragHarness;

internal sealed class HarnessForm : Form
{
    private readonly ListBox _receivedFiles;

    internal HarnessForm()
    {
        Text = "PWADrop drag harness";
        Size = new Size(900, 520);
        StartPosition = FormStartPosition.CenterScreen;
        BackColor = Color.FromArgb(245, 247, 252);
        Font = new Font("Segoe UI", 10f);

        var title = new Label
        {
            Text = "Original-drag priming test",
            Font = new Font(Font.FontFamily, 20f, FontStyle.Bold),
            AutoSize = true,
            Location = new Point(34, 28)
        };
        var instructions = new Label
        {
            Text = "Run PWADrop, then drag the source card to the .NET WinForms target. PWADrop primes delayed CF_HDROP and gets out of the way; the target receives that same original drag as physical files.",
            AutoEllipsis = true,
            Location = new Point(38, 74),
            Size = new Size(810, 48),
            ForeColor = Color.FromArgb(84, 91, 108)
        };

        var source = CreateCard("DRAG FROM HERE", "Delayed Chromium-style CF_HDROP", Color.FromArgb(77, 91, 255));
        source.Location = new Point(38, 145);
        source.MouseDown += BeginVirtualDrag;
        foreach (Control child in source.Controls)
        {
            child.MouseDown += BeginVirtualDrag;
        }

        var target = CreateCard("DROP INTO WINFORMS", "Only normal FileDrop paths are accepted", Color.FromArgb(30, 168, 120));
        target.Location = new Point(470, 145);
        target.AllowDrop = true;
        target.DragEnter += TargetDragEnter;
        target.DragDrop += TargetDragDrop;
        foreach (Control child in target.Controls)
        {
            child.AllowDrop = true;
            child.DragEnter += TargetDragEnter;
            child.DragDrop += TargetDragDrop;
        }

        _receivedFiles = new ListBox
        {
            Location = new Point(38, 340),
            Size = new Size(810, 112),
            BorderStyle = BorderStyle.FixedSingle
        };
        _receivedFiles.Items.Add("No physical files received yet.");

        Controls.Add(title);
        Controls.Add(instructions);
        Controls.Add(source);
        Controls.Add(target);
        Controls.Add(_receivedFiles);
    }

    private static Panel CreateCard(string title, string subtitle, Color accent)
    {
        var panel = new Panel
        {
            Size = new Size(378, 160),
            BackColor = Color.White,
            Cursor = Cursors.Hand
        };
        var accentBar = new Panel { Dock = DockStyle.Left, Width = 8, BackColor = accent };
        var titleLabel = new Label
        {
            Text = title,
            Font = new Font("Segoe UI", 15f, FontStyle.Bold),
            AutoSize = true,
            Location = new Point(34, 42)
        };
        var subtitleLabel = new Label
        {
            Text = subtitle,
            AutoSize = true,
            Location = new Point(36, 86),
            ForeColor = Color.FromArgb(84, 91, 108)
        };
        panel.Controls.Add(accentBar);
        panel.Controls.Add(titleLabel);
        panel.Controls.Add(subtitleLabel);
        return panel;
    }

    private static void BeginVirtualDrag(object? sender, MouseEventArgs eventArgs)
    {
        if (eventArgs.Button != MouseButtons.Left)
        {
            return;
        }

        var eml = Encoding.UTF8.GetBytes(
            "From: sender@example.test\r\n" +
            "To: agent@example.test\r\n" +
            "Subject: PWADrop test conversation\r\n" +
            "Date: Wed, 29 Jul 2026 09:00:00 -0500\r\n" +
            "MIME-Version: 1.0\r\n" +
            "Content-Type: text/plain; charset=utf-8\r\n\r\n" +
            "This message was generated by the PWADrop drag harness.\r\n");
        var pdf = Encoding.ASCII.GetBytes("%PDF-1.4\n% PWADrop virtual attachment harness\n%%EOF\n");
        using var dataObject = new VirtualFileDataObject(
            new VirtualTestFile("test-conversation.eml", eml),
            new VirtualTestFile("invoice.pdf", pdf));

        NativeMethods.DoDragDrop(
            dataObject,
            new MouseDropSource(dataObject),
            NativeMethods.DropEffectCopy,
            out _);
    }

    private static void TargetDragEnter(object? sender, DragEventArgs eventArgs)
    {
        eventArgs.Effect = eventArgs.Data?.GetDataPresent(DataFormats.FileDrop) == true
            ? DragDropEffects.Copy
            : DragDropEffects.None;
    }

    private void TargetDragDrop(object? sender, DragEventArgs eventArgs)
    {
        _receivedFiles.Items.Clear();
        if (eventArgs.Data?.GetData(DataFormats.FileDrop) is not string[] files || files.Length == 0)
        {
            _receivedFiles.Items.Add("Drop arrived without physical file paths.");
            return;
        }

        foreach (var file in files)
        {
            _receivedFiles.Items.Add($"{Path.GetFileName(file)} — {new FileInfo(file).Length:N0} bytes — {file}");
        }
    }
}
